### PR TITLE
Recorded music seek bar added!

### PR DESCRIPTION
**Pull request by justinma246**
- Seek bar added & tested
- When music ends, play will appear again. Will restart song.

### CODE REVIEW

**Comment by justinma246** [comment]
related to: https://github.com/vivrekar/vibrato/issues/20
please feel free to redesign bar as necessary

**Comment by justinma246** [comment]
Added duration next to song - https://github.com/vivrekar/vibrato/issues/14

**Comment by zzyyzzzzy** [comment]
position of time updated

**Pull request merged**
